project_id = "slomrtdygughdpenilco"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions]
[functions.realtime-chat]
verify_jwt = false

[functions.send-slack-message]
verify_jwt = true

[functions.get-openai-key]
verify_jwt = false

[functions.get-slack-client-id]
verify_jwt = true

[functions.slack-oauth]
verify_jwt = true

[functions.process-audio]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false