project_id = "slomrtdygughdpenilco"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
port = 54325

[analytics]
enabled = true
port = 54327

[functions.slack-oauth]
verify_jwt = false

[functions.send-slack-message]
verify_jwt = false

[functions.get-slack-client-id]
verify_jwt = false

[functions.process-audio]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.chat-with-ai]
verify_jwt = false