// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slomrtdygughdpenilco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsb21ydGR5Z3VnaGRwZW5pbGNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxNzY2MzYsImV4cCI6MjA0OTc1MjYzNn0.17_EOTjhPEdqDiPUJujl1nTAij8W4kgvlZ4aJLrD6K8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);